# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Skeleton
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Footer settings

# Jekyll-asset settings
assets:
  sources:
    _assets/scss
  compress:
    css: scss
    js: uglifier
  features:
    automatic_img_alt: true
    automatic_img_size: false

exclude:
  - package.json
  - README.md
  - CNAME

# Build settings
markdown: kramdown
permalink: pretty
include: ["_pages"]

plugins:
  - jekyll-paginate
  - jekyll-assets
  - uglifier
  - jekyll-feed
